### ISSUE TITLE
Hookup

### ISSUE THREAD

**Issue by AndrewMoneronGenex** [kellerza/python-ids-alarm#1]
Hi

I also want to play around with my IDS. Did you manage to inject data in to bus?

Can you share your device hookup? Is it necessary to use the MAX485 or can the FTDI  cable be connected directly to the alarm D+ D- bus.

**Comment by kellerza** [comment]
Hi @AndrewMoneronGenex You will need a RS485 driver, since the differential levels might not be enough to trigger your FTDI device (or might be too high, but I think this is unlikely)

I used a MAX485E DIP8 package & connected directly to the data bus that goes to the keypads (D+/D- on the IDS?). The DIP package should be easy enough to attach to the FTDI board:

FTDI | MAX485E | IDS
-----|------------|-----
GND | RE & GND |
Rx | RO |
Tx | DI |
5V | DE & VCC |
. | B | D+
. | A | D-

In order to inject data into the bus you will likely spoof yourself as one of the existing keypads.
